version: 0.2

phases:
  install:
    runtime-versions:
      java: Corretto21
    pre_build:
      commands:
        - sudo apt-get update; sudo apt-get install -y java-21-amazon-corretto-jdk
  build:
    commands:
      - mvn clean install
  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - target/*.jar
  discard-paths: yes
